import './global.css';

import { Inter } from '@next/font/google';

const font = Inter();

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className={font.className}>
			<head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</head>
			<body className='bg-gray-100'>{children}</body>
		</html>
	);
}
